/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TestGeminiapiIndexImport } from './routes/test-geminiapi.index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestGeminiapiIndexRoute = TestGeminiapiIndexImport.update({
  id: '/test-geminiapi/',
  path: '/test-geminiapi/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/test-geminiapi/': {
      id: '/test-geminiapi/'
      path: '/test-geminiapi'
      fullPath: '/test-geminiapi'
      preLoaderRoute: typeof TestGeminiapiIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test-geminiapi': typeof TestGeminiapiIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test-geminiapi': typeof TestGeminiapiIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/test-geminiapi/': typeof TestGeminiapiIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test-geminiapi'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test-geminiapi'
  id: '__root__' | '/' | '/test-geminiapi/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestGeminiapiIndexRoute: typeof TestGeminiapiIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestGeminiapiIndexRoute: TestGeminiapiIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/test-geminiapi/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/test-geminiapi/": {
      "filePath": "test-geminiapi.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
