/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as TestIndexImport } from './routes/test/index'
import { Route as HistoryIndexImport } from './routes/history/index'
import { Route as ChatingIndexImport } from './routes/chating/index'
import { Route as TestGeminiImport } from './routes/test/gemini'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TestIndexRoute = TestIndexImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryIndexRoute = HistoryIndexImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRoute,
} as any)

const ChatingIndexRoute = ChatingIndexImport.update({
  id: '/chating/',
  path: '/chating/',
  getParentRoute: () => rootRoute,
} as any)

const TestGeminiRoute = TestGeminiImport.update({
  id: '/test/gemini',
  path: '/test/gemini',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/test/gemini': {
      id: '/test/gemini'
      path: '/test/gemini'
      fullPath: '/test/gemini'
      preLoaderRoute: typeof TestGeminiImport
      parentRoute: typeof rootRoute
    }
    '/chating/': {
      id: '/chating/'
      path: '/chating'
      fullPath: '/chating'
      preLoaderRoute: typeof ChatingIndexImport
      parentRoute: typeof rootRoute
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexImport
      parentRoute: typeof rootRoute
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/test/gemini': typeof TestGeminiRoute
  '/chating': typeof ChatingIndexRoute
  '/history': typeof HistoryIndexRoute
  '/test': typeof TestIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/test/gemini': typeof TestGeminiRoute
  '/chating': typeof ChatingIndexRoute
  '/history': typeof HistoryIndexRoute
  '/test': typeof TestIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/test/gemini': typeof TestGeminiRoute
  '/chating/': typeof ChatingIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/test/': typeof TestIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/test/gemini' | '/chating' | '/history' | '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/test/gemini' | '/chating' | '/history' | '/test'
  id: '__root__' | '/' | '/test/gemini' | '/chating/' | '/history/' | '/test/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TestGeminiRoute: typeof TestGeminiRoute
  ChatingIndexRoute: typeof ChatingIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  TestIndexRoute: typeof TestIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TestGeminiRoute: TestGeminiRoute,
  ChatingIndexRoute: ChatingIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  TestIndexRoute: TestIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/test/gemini",
        "/chating/",
        "/history/",
        "/test/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/test/gemini": {
      "filePath": "test/gemini.tsx"
    },
    "/chating/": {
      "filePath": "chating/index.tsx"
    },
    "/history/": {
      "filePath": "history/index.tsx"
    },
    "/test/": {
      "filePath": "test/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
